//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OrganizerApp.WebUI.Infrastructure.Resources.Languages {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class LocalizedText {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal LocalizedText() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("OrganizerApp.WebUI.Infrastructure.Resources.Languages.LocalizedText", typeof(LocalizedText).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Aktywne projekty.
        /// </summary>
        public static string ActiveProjects {
            get {
                return ResourceManager.GetString("ActiveProjects", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nie znaleziono aktywnych projektów.
        /// </summary>
        public static string ActiveProjectsNotFound {
            get {
                return ResourceManager.GetString("ActiveProjectsNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wszystkie projekty.
        /// </summary>
        public static string AllProjects {
            get {
                return ResourceManager.GetString("AllProjects", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Przepraszamy, ale odpowiedź na Twoje żądanie nie istnieje..
        /// </summary>
        public static string BadRequestPrompt {
            get {
                return ResourceManager.GetString("BadRequestPrompt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ukończone projekty.
        /// </summary>
        public static string CompletedProjects {
            get {
                return ResourceManager.GetString("CompletedProjects", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ukończone zadania.
        /// </summary>
        public static string CompletedTasks {
            get {
                return ResourceManager.GetString("CompletedTasks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Utwórz projekt.
        /// </summary>
        public static string CreateProject {
            get {
                return ResourceManager.GetString("CreateProject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Utwórz zadanie.
        /// </summary>
        public static string CreateTask {
            get {
                return ResourceManager.GetString("CreateTask", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Usunięte projekty.
        /// </summary>
        public static string DeletedProjects {
            get {
                return ResourceManager.GetString("DeletedProjects", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Usunięte zadania.
        /// </summary>
        public static string DeletedTasks {
            get {
                return ResourceManager.GetString("DeletedTasks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Czas wykonania.
        /// </summary>
        public static string ExecutionTime {
            get {
                return ResourceManager.GetString("ExecutionTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Przepraszamy, ale nie możemy zwrócić Tobie tego zasobu..
        /// </summary>
        public static string ForbiddenPrompt {
            get {
                return ResourceManager.GetString("ForbiddenPrompt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wysoki.
        /// </summary>
        public static string High {
            get {
                return ResourceManager.GetString("High", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Niski.
        /// </summary>
        public static string Low {
            get {
                return ResourceManager.GetString("Low", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Średni.
        /// </summary>
        public static string Medium {
            get {
                return ResourceManager.GetString("Medium", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tworzysz nowy projekt.
        /// </summary>
        public static string NewProjectCreating {
            get {
                return ResourceManager.GetString("NewProjectCreating", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tworzysz nowe zadanie.
        /// </summary>
        public static string NewTaskCreating {
            get {
                return ResourceManager.GetString("NewTaskCreating", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Najbliższe.
        /// </summary>
        public static string Next {
            get {
                return ResourceManager.GetString("Next", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Przykro nam, ale strona o podanym adresie nie istnieje..
        /// </summary>
        public static string NotFoundPrompt {
            get {
                return ResourceManager.GetString("NotFoundPrompt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Projekt: .
        /// </summary>
        public static string Project {
            get {
                return ResourceManager.GetString("Project", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Opis projektu.
        /// </summary>
        public static string ProjectDescription {
            get {
                return ResourceManager.GetString("ProjectDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Szczegóły projektu.
        /// </summary>
        public static string ProjectDetails {
            get {
                return ResourceManager.GetString("ProjectDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ten projekt nie zawiera żadnych zadań..
        /// </summary>
        public static string ProjectDoesntContatinAnyTasks {
            get {
                return ResourceManager.GetString("ProjectDoesntContatinAnyTasks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ten projekt nie istnieje..
        /// </summary>
        public static string ProjectDoesntExist {
            get {
                return ResourceManager.GetString("ProjectDoesntExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edytujesz projekt: .
        /// </summary>
        public static string ProjectEditing {
            get {
                return ResourceManager.GetString("ProjectEditing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nazwa projektu.
        /// </summary>
        public static string ProjectName {
            get {
                return ResourceManager.GetString("ProjectName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Projekty.
        /// </summary>
        public static string Projects {
            get {
                return ResourceManager.GetString("Projects", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nie znaleziono żadnych projektów..
        /// </summary>
        public static string ProjectsNotFound {
            get {
                return ResourceManager.GetString("ProjectsNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Przeszukaj projekty.
        /// </summary>
        public static string ProjectsSearch {
            get {
                return ResourceManager.GetString("ProjectsSearch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zadania projektu: .
        /// </summary>
        public static string ProjectTasks {
            get {
                return ResourceManager.GetString("ProjectTasks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zapisz.
        /// </summary>
        public static string Save {
            get {
                return ResourceManager.GetString("Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zaplanowane.
        /// </summary>
        public static string Scheduled {
            get {
                return ResourceManager.GetString("Scheduled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Szukaj.
        /// </summary>
        public static string Search {
            get {
                return ResourceManager.GetString("Search", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wyszukaj po frazie.
        /// </summary>
        public static string SearchByPhrase {
            get {
                return ResourceManager.GetString("SearchByPhrase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kiedyś/Może.
        /// </summary>
        public static string SomedayMaybe {
            get {
                return ResourceManager.GetString("SomedayMaybe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Opis zadania.
        /// </summary>
        public static string TaskDescription {
            get {
                return ResourceManager.GetString("TaskDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Szczegóły zadania.
        /// </summary>
        public static string TaskDetails {
            get {
                return ResourceManager.GetString("TaskDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to To zadanie nie istnieje..
        /// </summary>
        public static string TaskDoesntExist {
            get {
                return ResourceManager.GetString("TaskDoesntExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edytujesz zadanie: .
        /// </summary>
        public static string TaskEditing {
            get {
                return ResourceManager.GetString("TaskEditing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nazwa zadania.
        /// </summary>
        public static string TaskName {
            get {
                return ResourceManager.GetString("TaskName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zadania.
        /// </summary>
        public static string Tasks {
            get {
                return ResourceManager.GetString("Tasks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nie znaleziono żadnych zadań..
        /// </summary>
        public static string TasksNotFound {
            get {
                return ResourceManager.GetString("TasksNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Przeszukaj zadania.
        /// </summary>
        public static string TasksSearch {
            get {
                return ResourceManager.GetString("TasksSearch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dzisiaj.
        /// </summary>
        public static string Today {
            get {
                return ResourceManager.GetString("Today", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Przepraszamy. Wystąpił nieokreślony błąd wewnętrzny..
        /// </summary>
        public static string UnidentifiedPrompt {
            get {
                return ResourceManager.GetString("UnidentifiedPrompt", resourceCulture);
            }
        }
    }
}
